<h3>NumPy

<small>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [2]:
# Importing NumPy Library
import numpy as np

#### Numpy Array's

1-Dimensional Array

In [22]:
# 1-dimensional array
a1 = np.array([1,2,3,4,5])
print('1-D Array:',a1)

1-D Array: [1 2 3 4 5]


Array Attributes

<small>Shape is a attribute of a numpy array which gives its dimensions as a tuple

In [23]:
print('Shape:',a1.shape)

Shape: (5,)


<small>Dtype is a attribute of a numpy array to print the type of values stored in an array

In [24]:
print('Dtype:',a1.dtype)

Dtype: int32


<small>Size is a attribute of a numpy array that finds the number of elements in the array

In [25]:
print('Size:',a1.size)

Size: 5


2-Dimensional Array

In [26]:
#1 2-dimensional array
a2 = np.array([[1],[2],[3]])
print('2-D Array:\n',a2)
print('Shape:',a2.shape)

2-D Array:
 [[1]
 [2]
 [3]]
Shape: (3, 1)


In [27]:
#2 2-dimensional array
a3 = np.array([[1,2],[3,4]])
print('2-D Array:\n',a3)
print('Shape:',a3.shape)

2-D Array:
 [[1 2]
 [3 4]]
Shape: (2, 2)


Array of Zeros

In [28]:
a4 = np.zeros((3,3)) # By default the array is of type float
print('Array of Zeros:\n',a4)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Array of Ones

In [29]:
# Array of ones
a5 = np.ones((3,3), dtype = np.int64)
print('Array of Ones:\n',a5)

Array of Ones:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


Array of Constants

In [30]:
# Array of constant
a6 = np.full((3,5),5)
print('Array of Constant:\n',a6)

Array of Constant:
 [[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


3-Dimensional Array

<small>The three dimensions are (Channel, Row, Columns)

In [31]:
d = np.random.random((3,3,3))
print('3-D Array:\n',d)

3-D Array:
 [[[0.17079832 0.49494757 0.33598245]
  [0.23653356 0.44539679 0.70892805]
  [0.43774556 0.91267074 0.63023296]]

 [[0.49870664 0.33642378 0.76898853]
  [0.27658176 0.2291422  0.37975511]
  [0.85488406 0.61399018 0.71642766]]

 [[0.49582122 0.58630086 0.54020879]
  [0.66627811 0.151255   0.5197314 ]
  [0.98866813 0.96090084 0.19208467]]]


Identity Matrix

In [32]:
a7 = np.eye(4) # Its a square matrix
print('Identity Matrix:\n',a7)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Random Matrix

In [33]:
# Random Matrix
a8 = np.random.random((5,3))
print('Random Matrix:\n',a8)

Random Matrix:
 [[0.23144955 0.20426332 0.38728017]
 [0.60000343 0.52795126 0.23496432]
 [0.26808112 0.90437022 0.2678002 ]
 [0.69474919 0.7001037  0.93408752]
 [0.67605654 0.87147098 0.45973145]]


#### Slicing 

<small>Slicing is used to get a subset of values from the array

In [34]:
# 2-D Array 
print(a8)

[[0.23144955 0.20426332 0.38728017]
 [0.60000343 0.52795126 0.23496432]
 [0.26808112 0.90437022 0.2678002 ]
 [0.69474919 0.7001037  0.93408752]
 [0.67605654 0.87147098 0.45973145]]


In [35]:
# Logic: To print the last column
print('1:',a8[:,-1])
# Logic: To print the values in last two columns of the last row
print('2:',a8[-1,1:])

1: [0.38728017 0.23496432 0.2678002  0.93408752 0.45973145]
2: [0.87147098 0.45973145]


In [36]:
# Logic: Reverse rows of a two dimensional array
print('3:',a8[::-1])
# Logic: Reverse columns of a two dimensional array
print('4:',a8[:,::-1])

3: [[0.67605654 0.87147098 0.45973145]
 [0.69474919 0.7001037  0.93408752]
 [0.26808112 0.90437022 0.2678002 ]
 [0.60000343 0.52795126 0.23496432]
 [0.23144955 0.20426332 0.38728017]]
4: [[0.38728017 0.20426332 0.23144955]
 [0.23496432 0.52795126 0.60000343]
 [0.2678002  0.90437022 0.26808112]
 [0.93408752 0.7001037  0.69474919]
 [0.45973145 0.87147098 0.67605654]]


In [37]:
# 3-D Array
print(d)

[[[0.17079832 0.49494757 0.33598245]
  [0.23653356 0.44539679 0.70892805]
  [0.43774556 0.91267074 0.63023296]]

 [[0.49870664 0.33642378 0.76898853]
  [0.27658176 0.2291422  0.37975511]
  [0.85488406 0.61399018 0.71642766]]

 [[0.49582122 0.58630086 0.54020879]
  [0.66627811 0.151255   0.5197314 ]
  [0.98866813 0.96090084 0.19208467]]]


In [38]:
# Logic: Reverse channels of a three dimensional array
# First Solution
print('5:',d[::-1])

5: [[[0.49582122 0.58630086 0.54020879]
  [0.66627811 0.151255   0.5197314 ]
  [0.98866813 0.96090084 0.19208467]]

 [[0.49870664 0.33642378 0.76898853]
  [0.27658176 0.2291422  0.37975511]
  [0.85488406 0.61399018 0.71642766]]

 [[0.17079832 0.49494757 0.33598245]
  [0.23653356 0.44539679 0.70892805]
  [0.43774556 0.91267074 0.63023296]]]


In [39]:
# Second Solution
print('6:',d[[2,1,0],:,:])

6: [[[0.49582122 0.58630086 0.54020879]
  [0.66627811 0.151255   0.5197314 ]
  [0.98866813 0.96090084 0.19208467]]

 [[0.49870664 0.33642378 0.76898853]
  [0.27658176 0.2291422  0.37975511]
  [0.85488406 0.61399018 0.71642766]]

 [[0.17079832 0.49494757 0.33598245]
  [0.23653356 0.44539679 0.70892805]
  [0.43774556 0.91267074 0.63023296]]]


#### Mathematical Operations

Element Wise Operations

In [40]:
# Element-Wise Addition 
# Note: The shapes of the array's should be same
b1 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])
print('Addition:\n',b1+b2)

Addition:
 [[ 6  8]
 [10 12]]


In [41]:
# Element-Wise Multiplication
b1 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])
print('Multiplication:\n',b1*b2)

Multiplication:
 [[ 5 12]
 [21 32]]


Matrix Dot Product

In [42]:
# Matrix Multiplication or Dot Product
print(b1.dot(b2))
print(np.dot(b1,b2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Vector Dot Product

In [43]:
# Vectors are linear arrays and dot product of vectors gives a scaler
b3 = np.array([1,2,3,4])
b4 = np.array([5,6,7,8])
print(b3.dot(b4))

70


np.sum Function

In [44]:
# np.sum Function
print('Array:\n',b1)
# np.sum function prints the sum of all the values
print('np.sum:',np.sum(b1))

Array:
 [[1 2]
 [3 4]]
np.sum: 10


In [45]:
# np.sum function takes an additional parameter called the axis. Axis parameter can take two values. 
# Axis = 0 gives sum along the column
print('Sum(axis = 0):',np.sum(b1,axis = 0))
# Axis = 1 gives sum along the row
print('Sum(axis = 1):',np.sum(b1,axis = 1))

Sum(axis = 0): [4 6]
Sum(axis = 1): [3 7]


Sum Function

In [46]:
# Sum Function: Prints the sum along the columns (axis = 0)
print('Sum Function:',sum(b1))

Sum Function: [4 6]


#### Stacking 

<small>[Stacking](https://www.geeksforgeeks.org/numpy-stack-in-python/) concatenates two arrays and creates a new array which has 1 more dimension than the input arrays 

In [47]:
# Stacking 1-D Array: Outputs a two dimensional array when input is one dimensional
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
# Stacking horizontally - along the rows
print(np.stack((a,b), axis = 1))
# Stacking vertically = along the columns
print(np.stack((a,b), axis = 0))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [63]:
#  Stacking 2-D Array: Outputs a three dimensional array when input is two dimensional
a1 = np.arange(1,17).reshape(4,4)
a2 = np.arange(17,33).reshape(4,4)
print('Array1:\n',a1)
print('Array2:\n',a2)
# Axis = 0 means stacking channel wise (2,4,4)
# Axis = 1 means stacking row wise (4,2,4)
# Axis = 2 means stacking column wise (4,4,2)
print('\n',np.stack((a1,a2),axis = 1))

Array1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array2:
 [[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

 [[[ 1  2  3  4]
  [17 18 19 20]]

 [[ 5  6  7  8]
  [21 22 23 24]]

 [[ 9 10 11 12]
  [25 26 27 28]]

 [[13 14 15 16]
  [29 30 31 32]]]


Hstack, Vstack and Concatenate

<small><ol>
    <li> [hstack](https://www.geeksforgeeks.org/numpy-hstack-in-python/) is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array. Hstack will not increase the dimension and will maintain the input shape of an array
    <li> [vstack](https://www.geeksforgeeks.org/numpy-vstack-in-python/) is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array, Vstack will not increase the dimension and will maintain the input shape of an array
    <li> [concatenate](https://www.geeksforgeeks.org/numpy-concatenate-function-python/) is used to concatenate the sequence of arrays. It maintains the input shape of the array.

In [49]:
# Horizontal Stack 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.hstack((a,b)))

[1 2 3 4 5 6 7 8]


#### Reshape

<b> <small>Difference between Reshape and Resize </b>
 <br>
<small> Both the numpy.reshape() and numpy.resize() methods are used to change the size of a NumPy array. The difference between them is that the reshape() does not changes the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array.

In [50]:
# Reshape a Numpy Array: 
# Below array contains 8 elements. Reshaping will always be done in one of the multiple of 8
c = np.stack((a,b), axis = 0)
print(c)
# Scenario-1
c = c.reshape(4,2) # 4x2 = 8
print(c)
# Scenario-2
c = c.reshape(8,) # 8x1 = 8
print(c)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


In [51]:
# Scenario-3
# We can specify any one of the dimensions and keep the other dimension as -1. Python runtime will automatically calulate the other dimension
c = c.reshape(8,-1)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


#### Flatten Function

The flatten() function is used to get a copy of an given array collapsed into one dimension

In [52]:
a1 = np.arange(1,17).reshape(4,4)
print(a1)
print(a1.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#### Arange Function

We use arange function to generate an array in a given range 

In [53]:
d1 = np.arange(10)
print(d1)
# Takes three parameters - Start, Stop, Step
d2 = np.arange(5,21,2)
print(d2)

[0 1 2 3 4 5 6 7 8 9]
[ 5  7  9 11 13 15 17 19]


#### Numpy Random Module

Shuffle Function

 <small>Used to Shuffle the content of an array - Doesn't return any value

In [54]:
np.random.shuffle(a)
print(d1)

[0 1 2 3 4 5 6 7 8 9]


Rand, Randn, Randint

In [65]:
# Rand - returns random values in a given shape
print(np.random.rand(2,3))
# Randn - returns random values from a standard normal distribution
print(np.random.randn(2,3))
# Randint - returns values in a given range
print(np.random.randint(5,10,3))

[[0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]]
[[ 0.3190391  -0.24937038  1.46210794]
 [-2.06014071 -0.3224172  -0.38405435]]
[6 6 6]


Choice Function

In [66]:
# Choice - to randomly pick an element from an array
print(np.random.choice([1,2,3,4,5,6]))

2


Seed Function

<small><ul>
    <li>Seed is used to initialize our random number generator. 
    <li>We need to set a seed number if we want our random number generator to generate the same value everytime
    <li>Seed function is used to store the state of a random machine

In [56]:
np.random.seed(1)
print(np.random.rand(2,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


#### Statistical Functions

In [57]:
# Min Function 
e1 = np.array([[1,2,3],[3,4,5]])
print(e1)
# Gives the minimum element in the array
print(np.min(e1))
# Minimum element across axis = 0 
print(np.min(e1,axis = 0))

[[1 2 3]
 [3 4 5]]
1
[1 2 3]


In [58]:
# Mean Function 
e1 = np.array([[1,2,3],[3,4,5]])
print(e1)
# Gives the mean of the array
print(np.mean(e1))
# Mean across axis = 0 
print(np.mean(e1,axis = 0))
# Mean using sum function
print(np.sum(e1)/(e1.shape[0]*e1.shape[1]))

[[1 2 3]
 [3 4 5]]
3.0
[2. 3. 4.]
3.0


In [59]:
# Median Function 
e1 = np.array([[1,2,3],[3,4,5]])
print(e1)
# Gives the median of the array
print(np.median(e1))

[[1 2 3]
 [3 4 5]]
3.0


In [60]:
# Average Function - Average is Weighted as compared to mean function 
w = np.array([1,2,3,4,5])
weights = [1,2,3,4,5]
print(np.average(w,weights = weights))

3.6666666666666665


In [61]:
# Standard Deviation
print(np.std(w))
# Standard Deviation without using function
x = np.mean(w)
std = np.sqrt(np.mean(abs(w-x)**2))
print(std)

1.4142135623730951
1.4142135623730951


#### Transposing

In [74]:
# Original Array
a = np.arange(0,6).reshape(3,2)
print(a)
print('Shape:',a.shape)
# Transpose
print(a.T)
print('Shape:',a.T.shape)

[[0 1]
 [2 3]
 [4 5]]
Shape: (3, 2)
[[0 2 4]
 [1 3 5]]
Shape: (2, 3)


#### Argmax

Argmax returns the indices of the maximum value along a axis

In [83]:
# Array
print(a)
# Indices of maximum value along the row
print(a.argmax(axis = 1))

[[0 1]
 [2 3]
 [4 5]]
[1 1 1]


#### Typecasting 

Used to change the type of the array

In [87]:
# Array
print(a)
# Typecast array to float. Does not change it inplace
print(a.astype('float64'))

[[0 1]
 [2 3]
 [4 5]]
[[0. 1.]
 [2. 3.]
 [4. 5.]]


#### Condtional Indexing

In [99]:
# Array
b = np.arange(0,30).reshape(6,-1)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [101]:
# Logic: Print values greater the 25 or less than 5
print((b>25) | (b<5))
print(b[(b>25) | (b<5)])

[[ True  True  True  True  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True  True  True  True]]
[ 0  1  2  3  4 26 27 28 29]


In [97]:
# Logic: Print values greater the 25 or less than 5 - Using np.where
print(b[np.where((b>25) | (b<5))])

[ 0  1  2  3  4 26 27 28 29]


In [102]:
# Logic: Assigning value 30 to all the the values greater than 25
b[(b>25)] = 30
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 30 30 30 30]]


#### Enumerate Function

Enumerate takes a iterable, adds a counter to the iterable and returns an enumerate object

In [103]:
for i, row in enumerate(b):
        print("Row {} is {}".format(i, row))

Row 0 is [0 1 2 3 4]
Row 1 is [5 6 7 8 9]
Row 2 is [10 11 12 13 14]
Row 3 is [15 16 17 18 19]
Row 4 is [20 21 22 23 24]
Row 5 is [25 30 30 30 30]


#### Zip Function

The zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together, and then the second item in each passed iterator are paired together etc.

In [104]:
for i,j in zip(b, b+1):
    print(i, '+', j, '=', i+j)

[0 1 2 3 4] + [1 2 3 4 5] = [1 3 5 7 9]
[5 6 7 8 9] + [ 6  7  8  9 10] = [11 13 15 17 19]
[10 11 12 13 14] + [11 12 13 14 15] = [21 23 25 27 29]
[15 16 17 18 19] + [16 17 18 19 20] = [31 33 35 37 39]
[20 21 22 23 24] + [21 22 23 24 25] = [41 43 45 47 49]
[25 30 30 30 30] + [26 31 31 31 31] = [51 61 61 61 61]


In [105]:
list(zip(b,b+1))

[(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5])),
 (array([5, 6, 7, 8, 9]), array([ 6,  7,  8,  9, 10])),
 (array([10, 11, 12, 13, 14]), array([11, 12, 13, 14, 15])),
 (array([15, 16, 17, 18, 19]), array([16, 17, 18, 19, 20])),
 (array([20, 21, 22, 23, 24]), array([21, 22, 23, 24, 25])),
 (array([25, 30, 30, 30, 30]), array([26, 31, 31, 31, 31]))]

#### Unique Function

<small> Gives the number of unique values and there count

In [5]:
a = np.round(np.random.randn(100))
print(a)

# Unique values
np.unique(a,return_counts=True)

[ 2. -1.  2.  1. -0.  0.  0. -1.  0. -1.  1. -0. -1.  0.  0.  1.  1.  2.
 -1.  1.  0.  0.  1.  1.  1. -0.  1.  1.  0.  0. -1. -1.  0. -0.  1. -3.
  1. -1. -1. -0. -0. -1.  0.  2. -0.  0.  0. -1.  0. -1.  1.  0.  0.  1.
 -1. -1.  0. -0. -0.  1. -1.  1.  0.  1.  0.  1.  0.  1. -1. -2.  2. -0.
 -0. -1. -0. -0.  1.  1.  1. -2.  0.  1.  1.  1. -2. -0.  1.  0.  0.  1.
 -1.  0.  1. -2. -0. -1. -0.  1. -0.  1.]


(array([-3., -2., -1.,  0.,  1.,  2.]),
 array([ 1,  4, 19, 41, 30,  5], dtype=int64))