<h3>NumPy

<small>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [81]:
# Importing NumPy Library
import numpy as np

##### Numpy Array's

In [153]:
# 1-dimensional array
a1 = np.array([1,2,3,4,5])
print('1-D Array:',a1)

1-D Array: [1 2 3 4 5]


In [203]:
# Shape is a attribute of a numpy array which gives its dimensions as a tuple
print('Shape:',a1.shape)
# Dtype is a attribute of a numpy array to print the type of values stored in an array
print('Dtype:',a1.dtype)
# Size is a attribute of a numpy array that finds the number of elements in the array
print('Size:',a1.size)

Shape: (5,)
Dtype: int32
Size: 5


In [156]:
#1 2-dimensional array
a2 = np.array([[1],[2],[3]])
print('2-D Array:\n',a2)
print('Shape:',a2.shape)

2-D Array:
 [[1]
 [2]
 [3]]
Shape: (3, 1)


In [158]:
#2 2-dimensional array
a3 = np.array([[1,2],[3,4]])
print('2-D Array:\n',a3)
print('Shape:',a3.shape)

2-D Array:
 [[1 2]
 [3 4]]
Shape: (2, 2)


In [162]:
# Array of zeros. 
# By default the array is of type float
a4 = np.zeros((3,3), dtype = np.float64)
print('Array of Zeros:\n',a4)

# Array of ones
a5 = np.ones((3,3), dtype = np.int64)
print('Array of Ones:\n',a5)

# Array of constant
a6 = np.full((3,5),5)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Array of Constant:
 [[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [184]:
# Three Dimensional Array - (Channel, Row, Column)
d = np.random.random((3,3,3))
print('3-D Array:\n',d)

3-D Array:
 [[[0.1653542  0.92750858 0.34776586]
  [0.7508121  0.72599799 0.88330609]
  [0.62367221 0.75094243 0.34889834]]

 [[0.26992789 0.89588622 0.42809119]
  [0.96484005 0.6634415  0.62169572]
  [0.11474597 0.94948926 0.44991213]]

 [[0.57838961 0.4081368  0.23702698]
  [0.90337952 0.57367949 0.00287033]
  [0.61714491 0.3266449  0.5270581 ]]]


In [163]:
# Its a square matrix
a7 = np.eye(4)
print('Identity Matrix:\n',a7)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [164]:
# Random Matrix
a8 = np.random.random((5,3))
print('Random Matrix:\n',a8)

Random Matrix:
 [[0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]
 [0.20445225 0.87811744 0.02738759]
 [0.67046751 0.4173048  0.55868983]
 [0.14038694 0.19810149 0.80074457]]


#### Slicing 

<small>Slicing is used to get a subset of values from the array

In [165]:
# 2-D Array 
print(a8)

[[0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]
 [0.20445225 0.87811744 0.02738759]
 [0.67046751 0.4173048  0.55868983]
 [0.14038694 0.19810149 0.80074457]]


In [171]:
# Last column
print('1:',a8[:,-1])
# Values in last two column of the last row
print('2:',a8[-1,1:])

1: [0.39676747 0.6852195  0.02738759 0.55868983 0.80074457]
2: [0.19810149 0.80074457]


In [174]:
# Reverse rows of a two dimensional array
print('3:',a8[::-1])
# Reverse columns of a two dimensional array
print('4:',a8[:,::-1])

3: [[0.14038694 0.19810149 0.80074457]
 [0.67046751 0.4173048  0.55868983]
 [0.20445225 0.87811744 0.02738759]
 [0.53881673 0.41919451 0.6852195 ]
 [0.18626021 0.34556073 0.39676747]]
4: [[0.39676747 0.34556073 0.18626021]
 [0.6852195  0.41919451 0.53881673]
 [0.02738759 0.87811744 0.20445225]
 [0.55868983 0.4173048  0.67046751]
 [0.80074457 0.19810149 0.14038694]]


In [190]:
# 3-D Array
print(d)

[[[0.27918368 0.58575927 0.96959575]
  [0.56103022 0.01864729 0.80063267]
  [0.23297427 0.8071052  0.38786064]]

 [[0.86354185 0.74712164 0.55624023]
  [0.13645523 0.05991769 0.12134346]
  [0.04455188 0.10749413 0.22570934]]

 [[0.71298898 0.55971698 0.01255598]
  [0.07197428 0.96727633 0.56810046]
  [0.20329323 0.25232574 0.74382585]]]


In [193]:
# Reverse channels of a three dimensional array
# First Solution
print('5:',d[::-1])

5: [[[0.71298898 0.55971698 0.01255598]
  [0.07197428 0.96727633 0.56810046]
  [0.20329323 0.25232574 0.74382585]]

 [[0.86354185 0.74712164 0.55624023]
  [0.13645523 0.05991769 0.12134346]
  [0.04455188 0.10749413 0.22570934]]

 [[0.27918368 0.58575927 0.96959575]
  [0.56103022 0.01864729 0.80063267]
  [0.23297427 0.8071052  0.38786064]]]


In [194]:
# Second Solution
print('6:',d[[2,1,0]])

6: [[[0.71298898 0.55971698 0.01255598]
  [0.07197428 0.96727633 0.56810046]
  [0.20329323 0.25232574 0.74382585]]

 [[0.86354185 0.74712164 0.55624023]
  [0.13645523 0.05991769 0.12134346]
  [0.04455188 0.10749413 0.22570934]]

 [[0.27918368 0.58575927 0.96959575]
  [0.56103022 0.01864729 0.80063267]
  [0.23297427 0.8071052  0.38786064]]]


#### Mathematical Operations

<small> Element Wise Operations

In [195]:
# Element-Wise Addition 
# Note: The shapes of the array's should be same
b1 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])
print('Addition:\n',b1+b2)

Addition:
 [[ 6  8]
 [10 12]]


In [196]:
# Element-Wise Multiplication
b1 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])
print('Multiplication:\n',b1*b2)

Multiplication:
 [[ 5 12]
 [21 32]]


<small> Dot Product

In [61]:
# Matrix Multiplication or Dot Product
print(b1.dot(b2))
print(np.dot(b1,b2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [62]:
# Vector Dot Product: Vectors are linear arrays and dot product of vectors gives a scaler
b3 = np.array([1,2,3,4])
b4 = np.array([5,6,7,8])
print(b3.dot(b4))

70


<small> Sum Function

In [200]:
# np.sum Function
print('Array:\n',b1)
# np.sum function prints the sum of all the values
print('np.sum:',np.sum(b1))
# np.sum function takes an additional parameter called the axis. Axis parameter can take two values. 
# Axis = 0 gives sum along the column
print('Sum(axis = 0):',np.sum(b1,axis = 0))
# Axis = 1 gives sum along the row
print('Sum(axis = 1):',np.sum(b1,axis = 1))

Array:
 [[1 2]
 [3 4]]
np.sum: 10
Sum(axis = 0): [4 6]
Sum(axis = 1): [3 7]


In [201]:
# Sum Function: Prints the sum along the columns (axis = 0)
print('Sum Function:',sum(b1))

Sum Function: [4 6]


<small> Stacking 

<small>[Stacking](https://www.geeksforgeeks.org/numpy-stack-in-python/) concatenates two array and creates a new array which has 1 more dimension than the input arrays 

In [202]:
# Stacking of Arrays: Concatenates the two arrays
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
# Stacking horizontally - along the rows
print(np.stack((a,b), axis = 1))
# Stacking vertically = along the columns
print(np.stack((a,b), axis = 0))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [218]:
# Stacking in case of 2-D Array
a1 = np.arange(1,17).reshape(4,4)
a2 = np.arange(17,33).reshape(4,4)
# Axis = 0 means stacking channel wise
# Axis = 1 means stacking row wise
# Axis = 2 means stacking column wise
print(np.stack((a1,a2),axis = 1))

[[[ 1  2  3  4]
  [17 18 19 20]]

 [[ 5  6  7  8]
  [21 22 23 24]]

 [[ 9 10 11 12]
  [25 26 27 28]]

 [[13 14 15 16]
  [29 30 31 32]]]


<small><ol>
    <li> [hstack](https://www.geeksforgeeks.org/numpy-hstack-in-python/) is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array
    <li> vstack is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array
    <li> [concatenate](https://www.geeksforgeeks.org/numpy-concatenate-function-python/) is used to concatenate the sequence of arrays. It maintains the input shape of the array.

In [221]:
# Horizontal Stack - Maintains the input shape of an array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.hstack((a,b)))

[1 2 3 4 5 6 7 8]


<small>Reshape

<small> Both the numpy.reshape() and numpy.resize() methods are used to change the size of a NumPy array. The difference between them is that the reshape() does not changes the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array.

In [223]:
# Reshape a Numpy Array: 
# Below array contains 8 elements. Reshaping will always be done in one of the multiple of 8
c = np.stack((a,b), axis = 0)
print(c)
c = c.reshape(4,2)
print(c)
c = c.reshape(8,)
print(c)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


In [222]:
# We can specify any one of the dimensions and keep the other dimension as -1. 
# Python runtime will automatically calulate the other dimension
c = c.reshape(8,-1)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


<small>Flatten Function

In [238]:
# The flatten() function is used to get a copy of an given array collapsed into one dimension
a1 = np.arange(1,17).reshape(4,4)
print(a1)
print(a1.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


<small> Arange Function

In [103]:
# We use arange function to generate an array in a given range 
d1 = np.arange(10)
print(d1)
# Takes three parameters - Start, Stop, Step
d2 = np.arange(5,21,2)
print(d2)

[0 1 2 3 4 5 6 7 8 9]
[ 5  7  9 11 13 15 17 19]


#### Numpy Random Module

In [115]:
# Shuffling the content of the array - Doesn't return any value
np.random.shuffle(a)
print(d1)

[0 6 5 1 2 8 7 9 3 4]


In [121]:
# Rand - returns random values in a given shape
print(np.random.rand(2,3))
# Randn - returns values from a standard normal distribution
print(np.random.randn(2,3))
# Randint - returns values in a given range
print(np.random.randint(5,10,3))
# Choice - to randomly pick an element from an array
print(np.random.choice([1,2,3,4,5,6]))

[[0.88705417 0.83446373 0.72029377]
 [0.50455933 0.21142082 0.34314058]]
[[ 0.71032391 -1.97635676 -1.38190525]
 [-0.211991    0.97808418  1.17056259]]
[6 7 7]
5


In [226]:
# Seed is used to initialize our random number generator. 
# We need to set a seed number if we want our random number generator to generate the same value everytime
# Seed function is used to store the state of a random machine
np.random.seed(1)
print(np.random.rand(2,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


#### Statistical Functions

In [138]:
# Min Function 
e1 = np.array([[1,2,3],[3,4,5]])
print(e1)
# Gives the minimum element in the array
print(np.min(e1))
# Minimum element across axis = 0 
print(np.min(e1,axis = 0))

[[1 2 3]
 [3 4 5]]
[[5 6 7]
 [7 8 9]]
1
[1 2 3]


In [143]:
# Mean Function 
e1 = np.array([[1,2,3],[3,4,5]])
print(e1)
# Gives the mean of the array
print(np.mean(e1))
# Mean across axis = 0 
print(np.mean(e1,axis = 0))
# Mean using sum function
print(np.sum(e1)/(e1.shape[0]*e1.shape[1]))

[[1 2 3]
 [3 4 5]]
3.0
[2. 3. 4.]
3.0


In [146]:
# Median Function 
e1 = np.array([[1,2,3],[3,4,5]])
print(e1)
# Gives the median of the array
print(np.median(e1))

[[1 2 3]
 [3 4 5]]
3.0


In [227]:
# Average Function - Average is Weighted as compared to mean function 
w = np.array([1,2,3,4,5])
weights = [1,2,3,4,5]
print(np.average(w,weights = weights))

3.6666666666666665


In [235]:
# Standard Deviation
print(np.std(w))
# Standard Deviation without using function
x = np.mean(w)
std = np.sqrt(np.mean(abs(w-x)**2))
print(std)

1.4142135623730951
1.4142135623730951
